baseURL = "https://hannuhartikainen.fi"
title = "Hannu Hartikainen"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
# pygmentsCodefences = true

enableEmoji = false

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = ""
title404 = "Nothing here!"

[params.assets]
favicon = "favicon.ico"
customCSS = []
customJS = []
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Hannu Hartikainen"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "2006-01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#3baeff"

[params.sidebar]
enable = false

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","taxonomy_cloud"]

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "dancek"
email = "hannu.hartikainen+hhfi@gmail.com"
facebook = ""
github = "dancek"
gitlab = "dancek"
instagram = ""
linkedin = "hannuhartikainen"
twitter = ""
telegram = ""
google_scholar = ""

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Repo"
weight = -10
identifier = "repository"
url = "https://github.com/dancek/hannuhartikainen.fi"
